# Generated by Django 3.1.3 on 2020-12-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='businessNum',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_business',
        ),
        migrations.AddField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('A', 'Admin'), ('B', 'Business'), ('C', 'Customer')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='businessType',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='store_ID',
            field=models.IntegerField(default=-1),
        ),
    ]
