# Generated by Django 3.1.3 on 2020-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='businessNum',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='businessType',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='store_ID',
            field=models.IntegerField(default=-1),
        ),
    ]
