# Generated by Django 3.1.3 on 2020-12-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='store',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='Store Address', max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='Store Name', max_length=150),
        ),
    ]
