# Generated by Django 3.1.3 on 2020-12-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201205_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='store_ID',
        ),
    ]
