# Generated by Django 3.1.3 on 2020-12-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='businessType',
        ),
    ]
