# Generated by Django 3.1.3 on 2020-12-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20201206_1725'),
        ('accounts', '0004_remove_account_businesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='store',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.store'),
        ),
    ]
