# Generated by Django 3.1.3 on 2020-12-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('store_address', models.CharField(default='', max_length=150)),
                ('store_status', models.CharField(choices=[('C', 'Confirmed'), ('AC', 'Awaiting confirmation'), ('DC', 'Declined confimation'), ('B', 'Banned')], default='AC', max_length=2)),
                ('businessNum', models.IntegerField(max_length=14, unique=True)),
                ('store_phone', models.IntegerField(max_length=14, unique=True)),
                ('category', models.CharField(choices=[('E', 'Electronics'), ('FS', 'Food Stuff'), ('T', 'Tools')], max_length=3)),
                ('store_ranking', models.IntegerField(default=0, max_length=1)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
