# Generated by Django 3.1.3 on 2020-12-06 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201206_1725'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='store',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='seller',
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='store',
            name='seller_ID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.IntegerField(max_length=14),
        ),
    ]
